# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('entidad', models.CharField(max_length=200)),
                ('cp', models.IntegerField()),
                ('latlng', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('rfc', models.CharField(max_length=200)),
                ('actividad', models.CharField(max_length=200)),
                ('expedicion_fecha', models.DateField()),
            ],
        ),
    ]
