# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configuraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_autoridad', models.CharField(max_length=200)),
                ('periodo_valido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('entidad', models.CharField(max_length=200)),
                ('cp', models.IntegerField()),
                ('latlng', models.CharField(blank=True, max_length=200)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('rfc', models.CharField(max_length=200)),
                ('actividad', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=200)),
                ('expedicion_fecha', models.DateField()),
                ('vencimiento_fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
