# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciatarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatarios',
            name='folio',
            field=models.CharField(max_length=200),
        ),
    ]
