# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciatarios', '0002_auto_20170131_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatarios',
            name='latlng',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
