# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciatarios', '0003_auto_20170131_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_autoridad', models.CharField(max_length=200)),
                ('periodo_valido', models.CharField(max_length=200)),
            ],
        ),
    ]
